/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tipula.glb')
  const mesh = useRef(null)
        useFrame(() => (mesh.current.rotation.z = mesh.current.rotation.z +=0.005))
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh ref = {mesh} geometry={nodes.Mesh_0001.geometry} material={nodes.Mesh_0001.material} rotation={[-Math.PI / 2, 0, 0]} scale = {[40,40,40]} />
    </group>
  )
}

useGLTF.preload('/tipula.glb')
