/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/pirateship.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=> 
  actions.waterWobble.play());
  useEffect(()=> 
  actions.shipWobble.play());
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-44.8, -7.69, 43.1]} rotation={[-0.08, -0.21, -0.25]}>
        <primitive object={nodes.Bone} />
        <skinnedMesh geometry={nodes.Plane.geometry} material={materials.Material} skeleton={nodes.Plane.skeleton} />
      </group>
      <group position={[-0.99, 1.53, 2.13]} rotation={[-1.56, -0.15, 0.19]}>
        <primitive object={nodes.Bone_1} />
        <skinnedMesh
          geometry={nodes.Cube002.geometry}
          material={materials['Material.001']}
          skeleton={nodes.Cube002.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube002_1.geometry}
          material={materials['Material.002']}
          skeleton={nodes.Cube002_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube002_2.geometry}
          material={materials['Material.003']}
          skeleton={nodes.Cube002_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube002_3.geometry}
          material={materials['Material.004']}
          skeleton={nodes.Cube002_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube002_4.geometry}
          material={materials['Material.005']}
          skeleton={nodes.Cube002_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Cube002_5.geometry}
          material={materials['Material.006']}
          skeleton={nodes.Cube002_5.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/pirateship.glb')
