/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/radio.glb");

  const mesh = useRef(null);
  useFrame(() => (mesh.current.rotation.y = mesh.current.rotation.y += 0.02));

  return (
    <group ref={mesh} scale={[0.2, 0.2, 0.2]} {...props} dispose={null}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Cube_2.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube_3.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Cube_4.geometry}
        material={materials["Material.003"]}
      />
    </group>
  );
}

useGLTF.preload("/radio.glb");
